# Spring Boot 配置
spring:
  application:
    name: ai-inspection
  
  # 数据源配置
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  # SQL脚本初始化
  sql:
    init:
      mode: embedded
      schema-locations: classpath:inspection_result.sql,classpath:inspection_prompt.sql,classpath:inspection_tag.sql
    
  # H2 控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # JPA配置（如果需要）
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    
# MyBatis配置
mybatis:
  # 指定mapper xml文件位置
  mapper-locations: classpath:mapper/*.xml
  # 指定实体类包路径
  type-aliases-package: org.example.entity
  # 配置
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 开启缓存
    cache-enabled: true
    # 开启延迟加载
    lazy-loading-enabled: true
    # 开启积极懒加载
    aggressive-lazy-loading: false
    # 允许多结果集
    multiple-result-sets-enabled: true
    # 使用列标签
    use-column-label: true
    # 使用生成的键
    use-generated-keys: true
    # 默认执行器类型
    default-executor-type: reuse
    # 默认语句超时时间
    default-statement-timeout: 25000

# 日志配置
logging:
  level:
    org.example.mapper: debug
    org.springframework.jdbc: debug
    org.mybatis: debug

# 巡检服务配置
app:
  env:
    type: dev

# DashScope API配置
dashscope:
  api:
    model: xxx
    key: xxx
    url: xxx

